name: Run Aze CLI Tests on PR

on:
  pull_request:
    branches:
      - main  

jobs:
  test:
    name: Run Aze CLI test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Don't need miden-node since we are using remote node now
      # - name: Checkout miden-node repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'RizeLabs/miden-node'
      #     path: 'miden-node'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # - name: Start miden node # start local miden node
      #   run: |
      #     cd miden-node
      #     cargo install --features testing --path bin/node # install miden-node binary
      #     cd bin/node
      #     miden-node make-genesis --force
      #     miden-node start node &
      
      # Run tests with logs enabled
      - name: Run tests
        run: cargo test --release -- --test-threads 1 --nocapture
